name: .NET CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'Server/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'Server/**'

jobs:
  build:
    name: Build Solution
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'

    - name: Cache NuGet packages
      uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Restore dependencies
      run: dotnet restore ./Server/BooksLab.sln

    - name: Build Solution
      run: dotnet build ./Server/BooksLab.sln --configuration Release --no-restore

    outputs:
      build_success: ${{ steps.build.outcome == 'success' }}

  test:
    name: Run Tests
    runs-on: windows-latest
    needs: build  # Зависит от успешного выполнения job 'build'

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'

    - name: Cache NuGet packages
      uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Restore dependencies (for tests)
      run: dotnet restore ./Server/BooksLab.sln

    - name: Run Tests
      run: dotnet test ./Server/BooksLab.sln --configuration Release --no-build --verbosity normal
