name: .NET CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'Server/**'  # Только при изменениях здесь
  pull_request:
    branches: [ "main"]
    paths:
      - 'Server/**'


jobs:
  NET-build-and-test:
    runs-on: windows-latest   # ubuntu-latest или windows-latest, macos-latest

    steps:
    - uses: actions/checkout@v4  # Клонирует репозиторий

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'  # Укажите вашу версию .NET (6.0, 7.0, 8.0)
    - name: Cache NuGet packages
      uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-
          
    - name: Restore dependencies
      run: dotnet restore ./Server/BooksLab.sln

    - name: Build
      run: dotnet build ./Server/BooksLab.sln --configuration Release --no-restore

    - name: Test
      run: dotnet test ./Server/BooksLab.sln --configuration Release --no-build --verbosity normal
