name: .NET CI

on:
  push:
    branches: [ "main", "lab2" ]
  pull_request:
    branches: [ "main", "lab2" ]

jobs:
  save-in-cloud:
    needs: test
    name: Push_to_Docker
    runs-on: ubuntu-latest
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0'  # Укажите вашу версию .NET

      - name: Login to Yandex Registry
        env:
          IMAGE_NAME: dino-server
          YC_TOKEN: ${{ secrets.YC_DOCKER_PASSWORD }}
          YC_CLOUD_ID: ${{ secrets.YC_CLOUD_ID }}
          YC_FOLDER_ID: ${{ secrets.YC_FOLDER_ID }}
        run: |
          echo "${{ secrets.YC_DOCKER_AUTH }}" | docker login --username json_key --password-stdin cr.yandex.ru

      - name: Build Docker image
        run: |
          docker build -t cr.yandex/crp10cd1h16114aqlaaj/dino-server:latest ./Server
      - name: Push to YCR
        run: |
          docker push cr.yandex/crp10cd1h16114aqlaaj/dino-server:latest
  build:
    name: Build Solution
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
      - name: Cache NuGet packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
      - name: Restore dependencies
        run: dotnet restore ./Server/BooksLab.sln
      - name: Build Solution
        run: dotnet build ./Server/BooksLab.sln --configuration Release --no-restore
        id: build
    outputs:
      build_success: ${{ steps.build.outcome == 'success' }}

  test:
    name: Run Tests
    runs-on: windows-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
      - name: Cache NuGet packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
      - name: Restore dependencies (for tests)
        run: dotnet restore ./Server/BooksLab.sln
      - name: Run Tests
        run: dotnet test ./Server/DinoTest/DinoTest.csproj
